---
enabled_features:
- lldp
- ospf
- bgp
- lacp
- pim
- vn-segment-vlan-based
- nv overlay
- fabric forwarding
- interface-vlan
- bfd

special_features:
- nv overlay evpn

loopbacks:
  - name: loopback0
    description: "Router ID"
  - name: loopback1
    description: "NVE source"
  - name: loopback100
    description: "Mutli-site VIP"

loopback_ips:
  - name: loopback0
    ipv4:
      address: "10.10.10.{{ ansible_host.split('.')[3] }}/32"
  - name: loopback1
    ipv4:
      address: "11.11.11.{{ ansible_host.split('.')[3] }}/32"
  - name: loopback100
    ipv4:
      address: "100.100.100.{{ ansible_host.split('.')[3] }}/32"
