device_info:
    dev_model: Nexus9000 C9500v Chassis ("Supervisor Module")
    dev_serial: 9XF1H1L03E6
    dev_vendor: Cisco
    os_version: 10.5(1)

interfaces:
-   description: Uplink to dub-st1-sp1
    enabled: true
    mtu: 9216
    name: port-channel1111
-   description: Uplink to dub-st1-sp2
    enabled: true
    mtu: 9216
    name: port-channel1112

l3_interfaces:
-   ipv4:
    -   address: 30.30.30.98/30
    name: port-channel1111
-   ipv4:
    -   address: 30.30.30.106/30
    name: port-channel1112

lag_interfaces:
-   members:
    -   member: Ethernet1/1
        mode: active
    -   member: Ethernet1/2
        mode: active
    name: port-channel1111
-   members:
    -   member: Ethernet1/3
        mode: active
    -   member: Ethernet1/4
        mode: active
    name: port-channel1112

