device_info:
    dev_model: Nexus9000 C9500v Chassis ("Supervisor Module")
    dev_serial: 9OFRLGGB40F
    dev_vendor: Cisco
    os_version: 10.5(1)
interfaces:
-   description: Downlink to dub-st1-sp1
    enabled: true
    mtu: 9216
    name: port-channel411
-   description: Downlink to dub-st1-sp2
    enabled: true
    mtu: 9216
    name: port-channel412
-   description: Downlink to dub-st2-sp1
    enabled: true
    mtu: 9216
    name: port-channel421
-   description: Downlink to dub-st2-sp2
    enabled: true
    mtu: 9216
    name: port-channel422
-   description: Downlink to dub-st3-sp1
    enabled: true
    mtu: 9216
    name: port-channel431
-   description: Downlink to dub-st3-sp2
    enabled: true
    mtu: 9216
    name: port-channel432
l3_interfaces:
-   ipv4:
    -   address: 30.30.30.73/30
    name: port-channel411
-   ipv4:
    -   address: 30.30.30.77/30
    name: port-channel412
-   ipv4:
    -   address: 30.30.30.81/30
    name: port-channel421
-   ipv4:
    -   address: 30.30.30.85/30
    name: port-channel422
-   ipv4:
    -   address: 30.30.30.89/30
    name: port-channel431
-   ipv4:
    -   address: 30.30.30.93/30
    name: port-channel432
lag_interfaces:
-   members:
    -   member: Ethernet1/1
        mode: active
    -   member: Ethernet1/2
        mode: active
    name: port-channel411
-   members:
    -   member: Ethernet1/3
        mode: active
    -   member: Ethernet1/4
        mode: active
    name: port-channel412
-   members:
    -   member: Ethernet1/5
        mode: active
    -   member: Ethernet1/6
        mode: active
    name: port-channel421
-   members:
    -   member: Ethernet1/7
        mode: active
    -   member: Ethernet1/8
        mode: active
    name: port-channel422
-   members:
    -   member: Ethernet1/9
        mode: active
    -   member: Ethernet1/10
        mode: active
    name: port-channel431
-   members:
    -   member: Ethernet1/11
        mode: active
    -   member: Ethernet1/12
        mode: active
    name: port-channel432

# BGP neighbors SSP <> SP
bgp_neighbors:
    - neighbor: 20.20.20.5
      description: "dub-st1-sp1"
      rr_client: true
    - neighbor: 20.20.20.6
      description: "dub-st1-sp2"
      rr_client: true
    - neighbor: 20.20.20.7
      description: "dub-st2-sp1"
      rr_client: true
    - neighbor: 20.20.20.8
      description: "dub-st2-sp2"
      rr_client: true
    - neighbor: 20.20.20.9
      description: "dub-st3-sp1"
      rr_client: true
    - neighbor: 20.20.20.10
      description: "dub-st3-sp2"
      rr_client: true
