device_info:
    dev_model: Nexus9000 C9500v Chassis ("Supervisor Module")
    dev_serial: 9PJGGK4QRWS
    dev_vendor: Cisco
    os_version: 10.5(1)
interfaces:
-   description: Downlink to dub-st1-sp1
    enabled: true
    mtu: 9216
    name: port-channel311
-   description: Downlink to dub-st1-sp2
    enabled: true
    mtu: 9216
    name: port-channel312
-   description: Downlink to dub-st2-sp1
    enabled: true
    mtu: 9216
    name: port-channel321
-   description: Downlink to dub-st2-sp2
    enabled: true
    mtu: 9216
    name: port-channel322
-   description: Downlink to dub-st3-sp1
    enabled: true
    mtu: 9216
    name: port-channel331
-   description: Downlink to dub-st3-sp2
    enabled: true
    mtu: 9216
    name: port-channel332
l3_interfaces:
-   ipv4:
    -   address: 30.30.30.49/30
    name: port-channel311
-   ipv4:
    -   address: 30.30.30.53/30
    name: port-channel312
-   ipv4:
    -   address: 30.30.30.57/30
    name: port-channel321
-   ipv4:
    -   address: 30.30.30.61/30
    name: port-channel322
-   ipv4:
    -   address: 30.30.30.65/30
    name: port-channel331
-   ipv4:
    -   address: 30.30.30.69/30
    name: port-channel332
lag_interfaces:
-   members:
    -   member: Ethernet1/1
        mode: active
    -   member: Ethernet1/2
        mode: active
    name: port-channel311
-   members:
    -   member: Ethernet1/3
        mode: active
    -   member: Ethernet1/4
        mode: active
    name: port-channel312
-   members:
    -   member: Ethernet1/5
        mode: active
    -   member: Ethernet1/6
        mode: active
    name: port-channel321
-   members:
    -   member: Ethernet1/7
        mode: active
    -   member: Ethernet1/8
        mode: active
    name: port-channel322
-   members:
    -   member: Ethernet1/9
        mode: active
    -   member: Ethernet1/10
        mode: active
    name: port-channel331
-   members:
    -   member: Ethernet1/11
        mode: active
    -   member: Ethernet1/12
        mode: active
    name: port-channel332

# BGP neighbors SSP <> SP
bgp_neighbors:
    - neighbor: 20.20.20.5
      description: "dub-st1-sp1"
      rr_client: true
    - neighbor: 20.20.20.6
      description: "dub-st1-sp2"
      rr_client: true
    - neighbor: 20.20.20.7
      description: "dub-st2-sp1"
      rr_client: true
    - neighbor: 20.20.20.8
      description: "dub-st2-sp2"
      rr_client: true
    - neighbor: 20.20.20.9
      description: "dub-st3-sp1"
      rr_client: true
    - neighbor: 20.20.20.10
      description: "dub-st3-sp2"
      rr_client: true
