device_info:
    dev_model: Nexus9000 C9500v Chassis ("Supervisor Module")
    dev_serial: 9O18AB69AN8
    dev_vendor: Cisco
    os_version: 10.5(1)

interfaces:
-   description: Uplink to dub-ssp1
    enabled: true
    mtu: 9216
    name: port-channel111
-   description: Uplink to dub-ssp2
    enabled: true
    mtu: 9216
    name: port-channel211
-   description: Uplink to dub-ssp3
    enabled: true
    mtu: 9216
    name: port-channel311
-   description: Uplink to dub-ssp4
    enabled: true
    mtu: 9216
    name: port-channel411
-   description: Downlink to dub-st1-lf1
    enabled: true
    mtu: 9216
    name: port-channel1111
-   description: Downlink to dub-st1-lf2
    enabled: true
    mtu: 9216
    name: port-channel1112

l3_interfaces:
-   ipv4:
    -   address: 30.30.30.2/30
    name: port-channel111
-   ipv4:
    -   address: 30.30.30.26/30
    name: port-channel211
-   ipv4:
    -   address: 30.30.30.50/30
    name: port-channel311
-   ipv4:
    -   address: 30.30.30.74/30
    name: port-channel411
-   ipv4:
    -   address: 30.30.30.97/30
    name: port-channel1111
-   ipv4:
    -   address: 30.30.30.101/30
    name: port-channel1112
    
lag_interfaces:
-   members:
    -   member: Ethernet1/1
        mode: active
    -   member: Ethernet1/2
        mode: active
    name: port-channel111
-   members:
    -   member: Ethernet1/3
        mode: active
    -   member: Ethernet1/4
        mode: active
    name: port-channel211
-   members:
    -   member: Ethernet1/5
        mode: active
    -   member: Ethernet1/6
        mode: active
    name: port-channel311
-   members:
    -   member: Ethernet1/7
        mode: active
    -   member: Ethernet1/8
        mode: active
    name: port-channel411
-   members:
    -   member: Ethernet1/9
        mode: active
    -   member: Ethernet1/10
        mode: active
    name: port-channel1111
-   members:
    -   member: Ethernet1/11
        mode: active
    -   member: Ethernet1/12
        mode: active
    name: port-channel1112

bgp_neighbors:
  # Upstream to all Superspines
  - neighbor: 20.20.20.1
    description: "dub-ssp1"
    rr_client: false
  
  - neighbor: 20.20.20.2
    description: "dub-ssp2"
    rr_client: false
  
  - neighbor: 20.20.20.3
    description: "dub-ssp3"
    rr_client: false
  
  - neighbor: 20.20.20.4
    description: "dub-ssp4"
    rr_client: false
  
  # Downstream to Site 1 Leafs (as RR server)
  - neighbor: 20.20.20.11
    description: "dub-st1-lf1"
    rr_client: true
  
  - neighbor: 20.20.20.12
    description: "dub-st1-lf2"
    rr_client: true
