device_info:
    dev_model: Nexus9000 C9500v Chassis ("Supervisor Module")
    dev_serial: 9BERDY8Q3M3
    dev_vendor: Cisco
    os_version: 10.5(1)

interfaces:
-   description: Uplink to dub-st2-sp1
    enabled: true
    mtu: 9216
    name: port-channel2121
-   description: Uplink to dub-st2-sp2
    enabled: true
    mtu: 9216
    name: port-channel2122

l3_interfaces:
-   ipv4:
    -   address: 30.30.30.118/30
    name: port-channel2121
-   ipv4:
    -   address: 30.30.30.126/30
    name: port-channel2122
    
lag_interfaces:
-   members:
    -   member: Ethernet1/1
        mode: active
    -   member: Ethernet1/2
        mode: active
    name: port-channel2121
-   members:
    -   member: Ethernet1/3
        mode: active
    -   member: Ethernet1/4
        mode: active
    name: port-channel2122
