---
### Device info
device_info:
    dev_model: Nexus9000 C9500v Chassis ("Supervisor Module")
    dev_serial: 9Z0OUHOIVL2
    dev_vendor: Cisco
    os_version: 10.5(1)

### Interface descriptions & MTU
interfaces:
-   description: Downlink to dub-st1-sp1
    enabled: true
    mtu: 9216
    name: port-channel111
-   description: Downlink to dub-st1-sp2
    enabled: true
    mtu: 9216
    name: port-channel112
-   description: Downlink to dub-st2-sp1
    enabled: true
    mtu: 9216
    name: port-channel121
-   description: Downlink to dub-st2-sp2
    enabled: true
    mtu: 9216
    name: port-channel122
-   description: Downlink to dub-st3-sp1
    enabled: true
    mtu: 9216
    name: port-channel131
-   description: Downlink to dub-st3-sp2
    enabled: true
    mtu: 9216
    name: port-channel132

### Interface IP addresses
l3_interfaces:
-   ipv4:
    -   address: 30.30.30.1/30
    name: port-channel111
-   ipv4:
    -   address: 30.30.30.5/30
    name: port-channel112
-   ipv4:
    -   address: 30.30.30.9/30
    name: port-channel121
-   ipv4:
    -   address: 30.30.30.13/30
    name: port-channel122
-   ipv4:
    -   address: 30.30.30.17/30
    name: port-channel131
-   ipv4:
    -   address: 30.30.30.21/30
    name: port-channel132

### Port channels
lag_interfaces:
-   members:
    -   member: Ethernet1/1
        mode: active
    -   member: Ethernet1/2
        mode: active
    name: port-channel111
-   members:
    -   member: Ethernet1/3
        mode: active
    -   member: Ethernet1/4
        mode: active
    name: port-channel112
-   members:
    -   member: Ethernet1/5
        mode: active
    -   member: Ethernet1/6
        mode: active
    name: port-channel121
-   members:
    -   member: Ethernet1/7
        mode: active
    -   member: Ethernet1/8
        mode: active
    name: port-channel122
-   members:
    -   member: Ethernet1/9
        mode: active
    -   member: Ethernet1/10
        mode: active
    name: port-channel131
-   members:
    -   member: Ethernet1/11
        mode: active
    -   member: Ethernet1/12
        mode: active
    name: port-channel132

# BGP neighbors SSP <> SP
bgp_neighbors:
    - neighbor: 20.20.20.5
      description: "dub-st1-sp1"
      rr_client: true
    - neighbor: 20.20.20.6
      description: "dub-st1-sp2"
      rr_client: true
    - neighbor: 20.20.20.7
      description: "dub-st2-sp1"
      rr_client: true
    - neighbor: 20.20.20.8
      description: "dub-st2-sp2"
      rr_client: true
    - neighbor: 20.20.20.9
      description: "dub-st3-sp1"
      rr_client: true
    - neighbor: 20.20.20.10
      description: "dub-st3-sp2"
      rr_client: true

