device_info:
    dev_model: Nexus9000 C9500v Chassis ("Supervisor Module")
    dev_serial: 9M6GPTBE8HI
    dev_vendor: Cisco
    os_version: 10.5(1)
interfaces:
-   description: Uplink to dub-st3-sp1
    enabled: true
    mtu: 9216
    name: port-channel3132
-   description: Uplink to dub-st3-sp2
    enabled: true
    mtu: 9216
    name: port-channel3232
l3_interfaces:
-   ipv4:
    -   address: 30.30.30.133/30
    name: port-channel3132
-   ipv4:
    -   address: 30.30.30.141/30
    name: port-channel3232
lag_interfaces:
-   members:
    -   member: Ethernet1/1
        mode: active
    -   member: Ethernet1/2
        mode: active
    name: port-channel3132
-   members:
    -   member: Ethernet1/3
        mode: active
    -   member: Ethernet1/4
        mode: active
    name: port-channel3232