device_info:
    dev_model: Nexus9000 C9500v Chassis ("Supervisor Module")
    dev_serial: 9RO4YSFKMFL
    dev_vendor: Cisco
    os_version: 10.5(1)

interfaces:
-   description: Uplink to dub-ssp1
    enabled: true
    mtu: 9216
    name: port-channel111
-   description: Uplink to dub-ssp2
    enabled: true
    mtu: 9216
    name: port-channel211
-   description: Uplink to dub-ssp3
    enabled: true
    mtu: 9216
    name: port-channel311
-   description: Uplink to dub-ssp4
    enabled: true
    mtu: 9216
    name: port-channel411
-   description: Downlink to dub-st2-lf1
    enabled: true
    mtu: 9216
    name: port-channel2121
-   description: Downlink to dub-st2-lf2
    enabled: true
    mtu: 9216
    name: port-channel2122

l3_interfaces:
-   ipv4:
    -   address: 30.30.30.10/30
    name: port-channel111
-   ipv4:
    -   address: 30.30.30.34/30
    name: port-channel211
-   ipv4:
    -   address: 30.30.30.58/30
    name: port-channel311
-   ipv4:
    -   address: 30.30.30.82/30
    name: port-channel411
-   ipv4:
    -   address: 30.30.30.113/30
    name: port-channel2121
-   ipv4:
    -   address: 30.30.30.117/30
    name: port-channel2122
    
lag_interfaces:
-   members:
    -   member: Ethernet1/1
        mode: active
    -   member: Ethernet1/2
        mode: active
    name: port-channel111
-   members:
    -   member: Ethernet1/3
        mode: active
    -   member: Ethernet1/4
        mode: active
    name: port-channel211
-   members:
    -   member: Ethernet1/5
        mode: active
    -   member: Ethernet1/6
        mode: active
    name: port-channel311
-   members:
    -   member: Ethernet1/7
        mode: active
    -   member: Ethernet1/8
        mode: active
    name: port-channel411
-   members:
    -   member: Ethernet1/9
        mode: active
    -   member: Ethernet1/10
        mode: active
    name: port-channel2121
-   members:
    -   member: Ethernet1/11
        mode: active
    -   member: Ethernet1/12
        mode: active
    name: port-channel2122

bgp_neighbors:
  # Upstream to all Superspines
  - neighbor: 20.20.20.1
    description: "dub-ssp1"
    rr_client: false
  
  - neighbor: 20.20.20.2
    description: "dub-ssp2"
    rr_client: false
  
  - neighbor: 20.20.20.3
    description: "dub-ssp3"
    rr_client: false
  
  - neighbor: 20.20.20.4
    description: "dub-ssp4"
    rr_client: false
  
  # Downstream to Site 1 Leafs (as RR server)
  - neighbor: 20.20.20.13
    description: "dub-st2-lf1"
    rr_client: true
  
  - neighbor: 20.20.20.14
    description: "dub-st2-lf2"
    rr_client: true

