---
- name: Add SSH host keys before connecting
  hosts: localhost
  gather_facts: no
  
  tasks:
    - name: Scan and add host keys
      shell: |
        ssh-keyscan -H {{ item }} >> ~/.ssh/known_hosts
      loop: "{{ ansible_host }}"
      delegate_to: localhost
      run_once: true
